### ISSUE TITLE
very narrow which-key pop-up window on emacs 27

### ISSUE THREAD

**Issue by emacs18** [justbur/emacs-which-key#241] opened 2020-02-29 21:08 UTC
On emacs 27 (but not on emacs 26), the side-window that pops up to display the
key bindings is very narrow (about 8 characters in width) for certain modes,
but not for others. The narrow display makes it impossible to read the function
names.

The narrow window pops up on all programming modes. For example if I type SPC
and wait a few seconds within C++ mode, I get the narrow side window. Same for
python mode, emacs-lisp mode, perl-mode, python-mode, as well as fundamental
mode.

However the side pop-up window is wide enough to read the function names for
these modes: shell, mail, dired, proced and message-mode.

If I explicitly change the major mode of any buffer to something else via M-x
command, then the which-key behavior does not change, e.g., if I start with say
python mode, then type 'M-x message-mode', then that buffer still pops up
narrow which-key buffer. Same for the other way around. If I start with a
buffer with message-mode, then change to python mode via 'M-x python-mode',
then which-key pop-up window is still not narrow. Thus the major mode that a
buffer starts with seems to dictate whether which-key window is narrow or not.

I have observed this behavior on my build of emacs 27 on ubuntu 18.04 for weeks
if not months. I have never observed this behavior on emacs 26.

I use latest develop branch of spacemacs and all latest versions of packages.

If someone can instruct me on how to debug this problem, I'll be eager work on this.
I would have switched from emacs 26 to 27 long ago if it were not for this problem.
So I'm very motivated to solve this problem.

**Comment by justbur** [comment] 2020-03-03 01:31
Thanks. I can reproduce this. It seems to be a bug introduced in `fit-window-to-buffer`. Since emacs 27 is not released yet, I'm not going to make major changes yet. 

You can avoid this by setting `which-key-allow-imprecise-window-fit` to `t`. The difference shouldn't be noticeable.

**Comment by justbur** [comment] 2020-03-05 13:48
The upstream bug appears to be fixed now on the emacs-27 branch. Please reopen if you have more trouble

**Closed by justbur** 2020-03-05 13:48 UTC
