### ISSUE TITLE
Using C-h to page when there is no next page causes error

### ISSUE THREAD

**Issue by kaushalmodi** [justbur/emacs-which-key#65] opened 2015-09-23 17:18 UTC
Consider these use cases:
- Let's say I press `C-c` and one page is enough to fit all the bindings. If I then do `C-h`, I get the below error.
- Let's say I press `C-x` and one page is not enough to fit all the bindings. If I then do `C-h`, I get the second page. But if I do `C-h` once again, I get the below error. *I was expecting the second `C-h` to show page 1 again.*

For these cases, I get this error:

> window-normalize-window: Lisp nesting exceeds ‘max-lisp-eval-depth’

I am using the latest version of `which-key` available on Melpa and the latest version of emacs from its git master branch.

**Comment by kaushalmodi** [comment] 2015-09-23 17:21
It's strange.. here's another variant of that error I just saw:

> unrecord-window-buffer: Lisp nesting exceeds ‘max-lisp-eval-depth’

**Comment by justbur** [comment] 2015-09-23 17:23
Have you seen [this](https://github.com/justbur/emacs-which-key#paging)? 

At that point `C-h` should now do what `C-h` does if you're in the middle of a prefix with which-key disabled. It might just show the bindings or you might be using something like `helm-descbinds`. Do you use that package?

That's indicating a detection of infinite recursion, but I don't use any recursive functions I don't think.

I can play with this and see if I can get it to reproduce.

**Comment by kaushalmodi** [comment] 2015-09-23 17:30
I don't have `helm-descbinds` installed.

I had read about the `C-h` for paging and have kept those vars at that default values.

But when I made the below change, the recursion error goes away:

```el
(setq which-key-prevent-C-h-from-cycling nil)  
```

**Comment by justbur** [comment] 2015-09-23 17:33
Which suggests it may not be a which-key problem, because with that variable equal to t when you hit `C-h` the last time, which-key calls `prefix-help-command` whatever that is set to for you. 

I will dig into this further

**Comment by kaushalmodi** [comment] 2015-09-23 17:34
Thanks. I will debug my init in binary fashion and post here when I find the problem (just in case someone else is facing the same issue).

**Comment by justbur** [comment] 2015-09-23 17:38
For whatever reason, I can't replicate it. If you use `toggle-debug-on-error` and post a backtrace it may help

**Comment by kaushalmodi** [comment] 2015-09-23 17:46
Tried `toggle-debug-on-error` before posting this issue.. surprisingly the \*Backtrace\* buffer opened but stayed empty.

By the way, I have set only `which-key-prevent-C-h-from-cycling` to nil; the `which-key-use-C-h-for-paging` var is still set to the default value `t`. So shouldn't `prefix-help-command` be set to `which-key-show-next-page`?

I'll post if edebugging `which-key-show-next-page` helps.

**Comment by justbur** [comment] 2015-09-23 17:48
Sorry I meant the value of `prefix-help-command` before which-key-mode is enabled.

Thanks for your help. I'd like to fix it if I can

**Comment by kaushalmodi** [comment] 2015-09-23 17:51
Hmm, interestingly `which-key--prefix-help-cmd-backup` is also set to `which-key-show-next-page`. So the value of `prefix-help-command` always stays `which-key-show-next-page`.

I'll debug more to understand how the backup var got corrupted.

**Comment by justbur** [comment] 2015-09-23 17:57
ah, that would explain the infinite recursion. Thanks, I'll look into that

**Comment by justbur** [comment] 2015-09-23 17:59
maybe I'll just call `describe-prefix-bindings` because `helm-descbinds` uses that too

**Comment by justbur** [comment] 2015-09-23 18:03
Please reopen if you run into this issue again, but it should be fixed. Thanks for the good information!

**Closed** 2015-09-23 18:02 UTC

**Comment by kaushalmodi** [comment] 2015-09-23 18:08
I confirm the fix; thanks for the quick back and forth with the debug.

**Comment by kaushalmodi** [comment] 2015-09-23 18:09
But I am still curious why you weren't able to recreate the bug. I use `use-package` to load the package. You can find my which-key setup [here][1] and see if you find anything as a suspect to this issue.

[1]: https://github.com/kaushalmodi/.emacs.d/blob/master/setup-files/setup-which-key.el

**Comment by justbur** [comment] 2015-09-23 18:15
I kind of remember you saying something a while back about running multiple instances of emacs? Maybe that's the reason we were getting different results. Probably related to [this](https://github.com/justbur/emacs-which-key/issues/38#issue-95220649)

**Comment by justbur** [comment] 2015-09-23 18:20
@kaushalmodi by the way, do you like the new behavior of `C-h` (now that it works)?

**Comment by kaushalmodi** [comment] 2015-09-23 18:25
Aha, it's not multiple instances of emacs. But emacs loading the saved session from the desktop file. So I think I know what's happening. You had that backup var as a global var. I think it should have been buffer local. That way when the desktop is enabling the which-key mode one by one in all the files it opens, the backup var eventually becomes equal to `which-key-show-next-page`.

> do you like the new behavior of C-h (now that it works)?

I might set `which-key-prevent-C-h-from-cycling` to nil, still not sure :)

**Comment by justbur** [comment] 2015-09-23 18:42
Well `prefix-help-command` is global, so the buffer-local thing wouldn't help. I should have just set the backup once initially, maybe in the `defvar` and not touched it afterwards. Anyway, I think the current method is a better and safer way to do things.

>I might set which-key-prevent-C-h-from-cycling to nil, still not sure :)
Probably depends on whether you used `C-h` before which-key at all. If you didn't there's no reason to make it available.
