### ISSUE TITLE
which-key--update error

### ISSUE THREAD

**Issue by justmytwospence** [justbur/emacs-which-key#101] opened 2016-02-09 02:17 UTC
Since one of the commits on February 3, I've been getting the following error any time which-key should be popping up:

```
Debugger entered--Lisp error: (wrong-type-argument char-or-string-p nil)
  which-key--show-page(0)
  which-key--create-buffer-and-show([32])
  which-key--update()
  apply(which-key--update nil)
  byte-code("r\301\302H\303H\"\210)\301\207" [timer apply 5 6] 4)
  timer-event-handler([t 0 1 0 t which-key--update nil idle 0])
```

**Comment by justbur** [comment] 2016-02-09 13:49
Hm, I haven't seen this and can't reproduce it. What settings are you using for which-key?

**Comment by justmytwospence** [comment] 2016-02-09 16:27
Ah. The problem only manifests when which-key-show-prefix is set to nil.

**Comment by justbur** [comment] 2016-02-09 16:34
I see the problem. Thanks for the report. Fixed in https://github.com/justbur/emacs-which-key/commit/0ca36cef48fc21b0a2c2a17ef310036c1fc051f9

**Closed** 2016-02-09 16:35 UTC

**Comment by runningskull** [comment] 2016-03-04 04:53
I'm now seeing this error when `which-key-show-prefix` is `'echo`, but it works properly when `nil`. (which-key is great btw. thx for it)

**Comment by justbur** [comment] 2016-03-04 14:15
@runningskull I think it has to be a different error than this one. Can you produce a backtrace and paste it in a new issue? Thanks
